### ISSUE TITLE
Porposal Example Format

### ISSUE THREAD

**Issue by yifan0707** [deco3500-2017/TeamBeyondBeingThere#10]
Suggested Format

structure:
Introduction: What is your project and what dilemma does it aim to address.
Concept: outline the idea and the rationale behind it. Define the project aims and audience and identify how your idea is different from / improves upon other current offerings. 

Identify areas of social & mobile theory that apply to, will inform your concept & approach.

Team: Who is on your team, what are their responsibilities, and how will you work together? List all the members and their course code.

Identify:
• Who will lead the team and manage the project;
• Who is responsible for logistics e.g. equipment, meetings, transport, etc;
• Who fills key roles, e.g. back end, front end, content, design;
• How will decisions be made;
• How will the team handle poor performance and resolve conflicts.

Communications: Where and when will your team meet and how will you all communicate? Where will files be stored and shared? What are the file naming conventions?
Identify the social platform/s your team has adopted and explain the choice. How will it facilitate communication or file sharing?

Plan: Identify the key tasks that need to be completed and when. Identify:
• Project phases e.g. research; requirements; design; construction;
• Key deliverables for each phase (Milestones); 
• Resources – equipment or other tools/people you might need.

Tags: Tag your proposed idea with 5 key concepts from social and mobile lectures (e.g. awareness, Collaboration, CSCW) and 2 keywords related to your domain.

**Comment by nan0221** [comment]
a readme.md editor: https://stackedit.io
